// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVgik5BcyAcrvhUQRmsQN7C5IFkS7vn0c',
    appId: '1:171715042864:web:34c8fac50d337f7d7657f5',
    messagingSenderId: '171715042864',
    projectId: 'velocitygo-a2fc0',
    authDomain: 'velocitygo-a2fc0.firebaseapp.com',
    storageBucket: 'velocitygo-a2fc0.firebasestorage.app',
    measurementId: 'G-FEP1PS9Q2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_5vuz0sk2VFpbV1IJI0cqlGdmEbvQanY',
    appId: '1:171715042864:android:b6384aa2af31ab957657f5',
    messagingSenderId: '171715042864',
    projectId: 'velocitygo-a2fc0',
    storageBucket: 'velocitygo-a2fc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMgq3S7LvwnkLyLXU9BV8TZ-EkKa2KRoA',
    appId: '1:171715042864:ios:43ce36b5506c52547657f5',
    messagingSenderId: '171715042864',
    projectId: 'velocitygo-a2fc0',
    storageBucket: 'velocitygo-a2fc0.firebasestorage.app',
    androidClientId: '171715042864-msal9h3sf81a168ir1n0vsu7o1j6tjrc.apps.googleusercontent.com',
    iosClientId: '171715042864-97h24n3pir615mu3rr6ks9p0sofqlp70.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalvel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMgq3S7LvwnkLyLXU9BV8TZ-EkKa2KRoA',
    appId: '1:171715042864:ios:43ce36b5506c52547657f5',
    messagingSenderId: '171715042864',
    projectId: 'velocitygo-a2fc0',
    storageBucket: 'velocitygo-a2fc0.firebasestorage.app',
    androidClientId: '171715042864-msal9h3sf81a168ir1n0vsu7o1j6tjrc.apps.googleusercontent.com',
    iosClientId: '171715042864-97h24n3pir615mu3rr6ks9p0sofqlp70.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalvel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVgik5BcyAcrvhUQRmsQN7C5IFkS7vn0c',
    appId: '1:171715042864:web:ea7db93567144baf7657f5',
    messagingSenderId: '171715042864',
    projectId: 'velocitygo-a2fc0',
    authDomain: 'velocitygo-a2fc0.firebaseapp.com',
    storageBucket: 'velocitygo-a2fc0.firebasestorage.app',
    measurementId: 'G-3GFFTC5SHW',
  );
}
